services:
  postgres:
    image: postgres:16.3-alpine
    ports: 
      - 5050:5432
    environment:
      POSTGRES_DB : shareitinerary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: shareitinerary
    ports:
      - 9090:9090
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareitinerary