version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  build:
    docker:
      - image: eclipse-temurin:22-alpine
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14    
      - run:
          name: Bulding the Jar file
          command: |
            ./gradlew clean build
  push:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14    
      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Multi-Arch Docker Images and push them on DockerHub
          command: |
            docker build -t $DOCKER_USERNAME/shareitinerary:amd64 --platform linux/amd64 .
            docker push $DOCKER_USERNAME/shareitinerary:amd64
            
      - run:
          name: Make docker manifest and push it on DockerHub 
          command: |
            docker manifest create $DOCKER_USERNAME/shareitinerary:latest $DOCKER_USERNAME/shareitinerary:amd64 $DOCKER_USERNAME/shareitinerary:arm64
            docker manifest push $DOCKER_USERNAME/shareitinerary:latest
            
  deploy-to-gke:
    docker:
      - image: cimg/gcp:2024.03.1
    steps:
      - checkout
      - run:
          name: authorizing with GCP
          command: |
            gcloud auth activate-service-account --key-file=<(echo "$GCP_KEY")
      - run:
          name: installing required utilities for the gcloud
          command: |
            sudo apt-get install kubectl
      - run:
          name: getting connected to cluster
          command: |
            gcloud container clusters get-credentials $CLUSTER_NAME --region us-central1 --project shareitinerary-prod
      - run:
          name: applying every k8s file to the deployment server
          command: |
            kubectl apply -f k8s/
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build          
      - push:
          context: dockerhub-creds
          requires:
            - build
      - hold:
          type: approval
          requires:
            - push
      - deploy-to-gke:
          requires:
            - hold
          context: gcp-creds
          filters:
            branches:
              only: main