version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:22.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/shareitinerary:latest .
      - run:
          name: Authenticate with DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker push $DOCKER_USERNAME/shareitinerary:latest

  # deploy-to-gke:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout
  #     - gcp-cli/install
  #     - gcp-cli/initialize
  #     - run:
  #         name: Deploy to GKE
  #         command: |
  #           gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_ZONE --project $GCP_PROJECT_ID
  #           kubectl apply -f k8s/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          context: dockerhub-creds
      # - deploy-to-gke:
      #     requires:
      #       - build-and-push
      #     context: gcp-creds
      #     filters:
      #       branches:
      #         only: main