kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-access-services-endpoints
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: access-services-endpoints
  apiGroup: rbac.authorization.k8s.io
